### Register Customer
POST http://localhost:8000/register
Content-Type: application/json

{
  "first_name": "Ahad",
  "last_name": "Khan",
  "monthly_income": 100000,
  "phone_number": "9876543211"
}



### Check Loan Eligibility
POST http://localhost:8000/check-eligibility
Content-Type: application/json

{
  "customer_id": 306,
  "loan_amount": 50000,
  "interest_rate": 10.5,
  "tenure": 24
}




### create loan
POST http://localhost:8000/create-loan
Content-Type: application/json

{
  "customer_id": 306,
  "loan_amount": 100000,
  "interest_rate": 10.5,
  "tenure": 12
}



### View Loan by ID
GET http://localhost:8000/view-loan/11
Content-Type: application/json

### View loan by customer ID
GET http://localhost:8000/view-loans/306
Content-Type: application/json


